### ISSUE TITLE
Fix the `combine_orthoani_results` module

### ISSUE THREAD

**Issue by emilyncosta** [emilyncosta/camila_sao_paulo_nf#2]
Hi @Mxrcon,

The following module is raising an error while running the pipeline at the moment for some reason, if possible could you please test this module in isolation using `stubs`?

https://github.com/bioinformatics-lab/camila_sao_paulo_nf/blob/main/modules/utils/combine_orthoani_results_tsv/combine_orthoani_results_tsv.nf

**Comment by Mxrcon** [comment]
@emilyncosta yes sure, I'll give test and return here
