### ISSUE TITLE
[FIX] typo on `params/local.yml`

### ISSUE THREAD

**Issue by Mxrcon** [emilyncosta/camila_sao_paulo_nf#6]
fixing typo on the `params/local.yml` file
_Originally posted by @Mxrcon in https://github.com/emilyncosta/labmicobact_unifesp_ntm_romagnoli_nf/pull/4#discussion_r716653255_

**Comment by Mxrcon** [comment]
@abhi18av please assign this issue to me

**Comment by abhi18av** [comment]
@Mxrcon , for future references. Fixing typos doesn't require issues :)

**Comment by Mxrcon** [comment]
ok :+1:
